name = "rald-control-center-api"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "rald-control-center-db"
database_id = "a904867c-083d-40b5-a230-12e2be0ac771"

[[routes]]
pattern = "api.control.rald.cloud/*"
zone_name = "rald.cloud"
